name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0114,C0103,C0115,C0116,C0301,C0415,C0412,R0903,W0613,W1401,R1705,C0325,R0801,E0213,R0913,E1136,W0237,W0707,W0622,E1102,R0911,R1710,E0402 src/**/*.py
