name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (only if not already installed)
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "No requirements.txt found, skipping dependency installation"
          else
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi
      - name: Run tests
        run: |
          make tests
